/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg3;

import java.util.HashMap;
import javax.swing.JFrame;

/**
 *
 * @author Nikki
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        setTitle("Registration");
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        R101b = new javax.swing.JButton();
        R102b = new javax.swing.JButton();
        R103b = new javax.swing.JButton();
        R104b = new javax.swing.JButton();
        R105b = new javax.swing.JButton();
        R106b = new javax.swing.JButton();
        R107b = new javax.swing.JButton();
        R108b = new javax.swing.JButton();
        R109b = new javax.swing.JButton();
        R110b = new javax.swing.JButton();
        R201b = new javax.swing.JButton();
        R202b = new javax.swing.JButton();
        R203b = new javax.swing.JButton();
        R204b = new javax.swing.JButton();
        R205b = new javax.swing.JButton();
        R206b = new javax.swing.JButton();
        R207b = new javax.swing.JButton();
        R208b = new javax.swing.JButton();
        R209b = new javax.swing.JButton();
        R210b = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextBox = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FirstNameBox = new javax.swing.JTextField();
        LastNameBox = new javax.swing.JTextField();
        ReserveDateBox1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ReserveDateBox2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        GuestBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        UsernameBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        RoomNumBox = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CreditCardBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ExpDateBox1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ExpDateBox2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CVVBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AddressBox1 = new javax.swing.JTextField();
        AddressBox2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        StateBox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ZipCodeBox = new javax.swing.JTextField();
        Confirmb = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadReserveb = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Exitb = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        R101b.setText("R101");
        R101b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R101bActionPerformed(evt);
            }
        });

        R102b.setText("R102");
        R102b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R102bActionPerformed(evt);
            }
        });

        R103b.setText("R103");
        R103b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R103bActionPerformed(evt);
            }
        });

        R104b.setText("R104");
        R104b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R104bActionPerformed(evt);
            }
        });

        R105b.setText("R105");
        R105b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R105bActionPerformed(evt);
            }
        });

        R106b.setText("R106");
        R106b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R106bActionPerformed(evt);
            }
        });

        R107b.setText("R107");
        R107b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R107bActionPerformed(evt);
            }
        });

        R108b.setText("R108");
        R108b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R108bActionPerformed(evt);
            }
        });

        R109b.setText("R109");
        R109b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R109bActionPerformed(evt);
            }
        });

        R110b.setText("R110");
        R110b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R110bActionPerformed(evt);
            }
        });

        R201b.setText("R201");
        R201b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R201bActionPerformed(evt);
            }
        });

        R202b.setText("R202");
        R202b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R202bActionPerformed(evt);
            }
        });

        R203b.setText("R203");
        R203b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R203bActionPerformed(evt);
            }
        });

        R204b.setText("R204");
        R204b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R204bActionPerformed(evt);
            }
        });

        R205b.setText("R205");
        R205b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R205bActionPerformed(evt);
            }
        });

        R206b.setText("R206");
        R206b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R206bActionPerformed(evt);
            }
        });

        R207b.setText("R207");
        R207b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R207bActionPerformed(evt);
            }
        });

        R208b.setText("R208");
        R208b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R208bActionPerformed(evt);
            }
        });

        R209b.setText("R209");
        R209b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R209bActionPerformed(evt);
            }
        });

        R210b.setText("R210");
        R210b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R210bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(R209b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R207b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R205b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R203b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R201b, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(R202b, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R204b, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R206b, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R208b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R210b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(R109b, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(R101b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R103b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R107b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R105b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R104b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R102b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R110b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R106b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R108b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R101b)
                    .addComponent(R102b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R103b)
                    .addComponent(R104b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R105b)
                    .addComponent(R106b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R107b)
                    .addComponent(R108b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R109b)
                    .addComponent(R110b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R201b)
                    .addComponent(R202b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R203b)
                    .addComponent(R204b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R205b)
                    .addComponent(R206b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R207b)
                    .addComponent(R208b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R209b)
                    .addComponent(R210b)))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg3/IconHotel.jpg"))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        InfoTextBox.setColumns(20);
        InfoTextBox.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        InfoTextBox.setRows(5);
        InfoTextBox.setText("Welcome! Please select a room for\ninformation and availability! We hope\nyou have a pleaseant stay!\n");
        jScrollPane1.setViewportView(InfoTextBox);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("First Name: ");

        jLabel3.setText("Last Name: ");

        jLabel4.setText("Reservation Dates: ");

        jLabel5.setText("to");

        jLabel6.setText("Number of Guests: ");

        jLabel7.setText("Username: ");

        jLabel11.setText("Room #: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(RoomNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReserveDateBox2)
                            .addComponent(ReserveDateBox1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameBox)
                            .addComponent(LastNameBox)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameBox)
                            .addComponent(GuestBox))))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(RoomNumBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FirstNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LastNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ReserveDateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReserveDateBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(GuestBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UsernameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setText("Credit Card #: ");

        jLabel9.setText("Exp. Date: ");

        jLabel10.setText("/");

        jLabel12.setText("CVV: ");

        jLabel13.setText("Address: ");

        jLabel14.setText("State: ");

        jLabel15.setText("Zip Code: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZipCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CreditCardBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AddressBox1)
                                .addComponent(AddressBox2)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CVVBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ExpDateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ExpDateBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CreditCardBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ExpDateBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ExpDateBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CVVBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(AddressBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(StateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ZipCodeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Confirmb.setText("Confirm");
        Confirmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmbActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        LoadReserveb.setText("Load Reservation");
        LoadReserveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadReservebActionPerformed(evt);
            }
        });
        jMenu1.add(LoadReserveb);
        jMenu1.add(jSeparator1);

        Exitb.setText("Exit");
        Exitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbActionPerformed(evt);
            }
        });
        jMenu1.add(Exitb);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmb, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Confirmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R101bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R101bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 101 includes: \n1 Bed\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("101");
    }//GEN-LAST:event_R101bActionPerformed

    private void R102bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R102bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 102 includes: \n1 Bed\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("102");
    }//GEN-LAST:event_R102bActionPerformed

    private void R103bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R103bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 103 includes: \n1 Bed\nTV\nMini Fridge\nMini Bar\nOcean-side View");
        RoomNumBox.setText("103");
    }//GEN-LAST:event_R103bActionPerformed

    private void R104bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R104bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 104 includes: \n1 Bed\nTV\nMini Fridge\nCity-side View");
        RoomNumBox.setText("104");
    }//GEN-LAST:event_R104bActionPerformed

    private void R105bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R105bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 105 includes: \n1 Bed\nTV\nMini Fridge\nMini Bar\nCity-side View");
        RoomNumBox.setText("105");
    }//GEN-LAST:event_R105bActionPerformed

    private void R106bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R106bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 106 includes: \n2 Beds\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("106");
    }//GEN-LAST:event_R106bActionPerformed

    private void R107bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R107bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 107 includes: \n2 Beds\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("107");
    }//GEN-LAST:event_R107bActionPerformed

    private void R108bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R108bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 108 includes: \n2 Beds\nTV\nMini Fridge\nMini Bar\nOcean-side View");
        RoomNumBox.setText("108");
    }//GEN-LAST:event_R108bActionPerformed

    private void R109bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R109bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 109 includes: \n2 Beds\nTV\nMini Fridge\nCity-side View");
        RoomNumBox.setText("109");
    }//GEN-LAST:event_R109bActionPerformed

    private void R110bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R110bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 110 includes: \n2 Beds\nTV\nMini Fridge\nMini Bar\nCity-side View");
        RoomNumBox.setText("110");
    }//GEN-LAST:event_R110bActionPerformed

    private void R201bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R201bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 201 includes: \n1 Bed\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("201");
    }//GEN-LAST:event_R201bActionPerformed

    private void R202bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R202bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 202 includes: \n1 Bed\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("202");
    }//GEN-LAST:event_R202bActionPerformed

    private void R203bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R203bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 203 includes: \n1 Bed\nTV\nMini Fridge\nMini Bar\nOcean-side View");
        RoomNumBox.setText("203");
    }//GEN-LAST:event_R203bActionPerformed

    private void R204bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R204bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 204 includes: \n1 Bed\nTV\nMini Fridge\nCity-side View");
        RoomNumBox.setText("204");
    }//GEN-LAST:event_R204bActionPerformed

    private void R205bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R205bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 205 includes: \n1 Bed\nTV\nMini Fridge\nMini Bar\nCity-side View");
        RoomNumBox.setText("205");
    }//GEN-LAST:event_R205bActionPerformed

    private void R206bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R206bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 206 includes: \n2 Beds\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("206");
    }//GEN-LAST:event_R206bActionPerformed

    private void R207bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R207bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 207 includes: \n2 Beds\nTV\nMini Fridge\nOcean-side View");
        RoomNumBox.setText("207");
    }//GEN-LAST:event_R207bActionPerformed

    private void R208bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R208bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 208 includes: \n2 Beds\nTV\nMini Fridge\nMini Bar\nOcean-side View");
        RoomNumBox.setText("208");
    }//GEN-LAST:event_R208bActionPerformed

    private void R209bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R209bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 209 includes: \n2 Beds\nTV\nMini Fridge\nCity-side View");
        RoomNumBox.setText("209");
    }//GEN-LAST:event_R209bActionPerformed

    private void R210bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R210bActionPerformed
        InfoTextBox.setText("");
        InfoTextBox.setText("Room 210 includes: \n2 Beds\nTV\nMini Fridge\nMini Bar\nCity-side View");
        RoomNumBox.setText("210");
    }//GEN-LAST:event_R210bActionPerformed

    private void ConfirmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmbActionPerformed
        Confirm c = new Confirm();
        c.setVisible(true);
        Confirm.ConfirmRoomNumBox.setText(Register.RoomNumBox.getText());
        Confirm.ConfirmReserveDateBox1.setText(Register.ReserveDateBox1.getText());
        Confirm.ConfirmReserveDateBox2.setText(Register.ReserveDateBox2.getText());
        Confirm.ConfirmUsernameBox.setText(Register.UsernameBox.getText());
    }//GEN-LAST:event_ConfirmbActionPerformed

    private void ExitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitbActionPerformed

    private void LoadReservebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadReservebActionPerformed
        Load l = new Load();
        l.setVisible(true);
    }//GEN-LAST:event_LoadReservebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    
    public void loadData(String rezID, String roomNum, String checkInDate, String checkOutDate)
    {
        
                RoomNumBox.setText(roomNum);
                ReserveDateBox1.setText(checkInDate);
                ReserveDateBox2.setText(checkOutDate);
                
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressBox1;
    private javax.swing.JTextField AddressBox2;
    private javax.swing.JTextField CVVBox;
    private javax.swing.JButton Confirmb;
    private javax.swing.JTextField CreditCardBox;
    private javax.swing.JMenuItem Exitb;
    private javax.swing.JTextField ExpDateBox1;
    private javax.swing.JTextField ExpDateBox2;
    private javax.swing.JTextField FirstNameBox;
    private javax.swing.JTextField GuestBox;
    private javax.swing.JTextArea InfoTextBox;
    private javax.swing.JTextField LastNameBox;
    private javax.swing.JMenuItem LoadReserveb;
    private javax.swing.JButton R101b;
    private javax.swing.JButton R102b;
    private javax.swing.JButton R103b;
    private javax.swing.JButton R104b;
    private javax.swing.JButton R105b;
    private javax.swing.JButton R106b;
    private javax.swing.JButton R107b;
    private javax.swing.JButton R108b;
    private javax.swing.JButton R109b;
    private javax.swing.JButton R110b;
    private javax.swing.JButton R201b;
    private javax.swing.JButton R202b;
    private javax.swing.JButton R203b;
    private javax.swing.JButton R204b;
    private javax.swing.JButton R205b;
    private javax.swing.JButton R206b;
    private javax.swing.JButton R207b;
    private javax.swing.JButton R208b;
    private javax.swing.JButton R209b;
    private javax.swing.JButton R210b;
    public static javax.swing.JTextField ReserveDateBox1;
    public static javax.swing.JTextField ReserveDateBox2;
    public static javax.swing.JTextField RoomNumBox;
    private javax.swing.JTextField StateBox;
    public static javax.swing.JTextField UsernameBox;
    private javax.swing.JTextField ZipCodeBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
